spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/olimp
    username: superadmin
    password: superadmin
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
